# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    oauth_custom_user_provider:
        class: Cekurte\Psr\CompatibilityBundle\Security\Core\User\FOSUBUserProvider
        arguments: [@fos_user.user_manager, {github: githubId}]
